=== NaGeLBailey/shadertastic/metadata_schema/meta.json.schema.json
{
  "$id": "meta.json",
  "$ref": "#/definitions/meta",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "ColorARGB": {
      "pattern": "^#([A-Fa-f0-9]{8})$",
      "type": "string"
    },
    "ColorRGB": {
      "pattern": "^#([A-Fa-f0-9]{6})$",
      "type": "string"
    },
    "meta": {
      "additionalProperties": false,
      "properties": {
        "about": {
          "additionalProperties": {
            "type": "string"
          },
          "description": "About information. You can add whatever you want next to the author name and the description of the effect",
          "properties": {
            "author_name": {
              "type": "string"
            },
            "author_url": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "author_name"
          ],
          "type": "object"
        },
        "input_facedetection": {
          "description": "DEPRECATED Old way of using the face detection parameter in the effect. Use `param_face_detection` instead",
          "type": "boolean"
        },
        "input_time": {
          "description": "DEPRECATED Old way of using a time parameter in the effect. Use `param_time` instead",
          "type": "boolean"
        },
        "label": {
          "description": "Name of the effect as shown in the OBS UI",
          "type": "string"
        },
        "metafileVersion": {
          "default": 1,
          "description": "Version of the meta file. Will be used in the future to migrate older meta files and keep the legacy code working",
          "type": "number"
        },
        "parameters": {
          "description": "Extra Paramters of the effect",
          "items": {
            "$ref": "#/definitions/param"
          },
          "type": "array"
        },
        "revision": {
          "description": "Revision number",
          "type": "number"
        },
        "steps": {
          "default": 0,
          "description": "Number of steps in the effect",
          "type": "number"
        }
      },
      "required": [
        "about",
        "label"
      ],
      "type": "object"
    },
    "param": {
      "anyOf": [
        {
          "$ref": "#/definitions/param_audiolevel"
        },
        {
          "$ref": "#/definitions/param_bool"
        },
        {
          "$ref": "#/definitions/param_color"
        },
        {
          "$ref": "#/definitions/param_float"
        },
        {
          "$ref": "#/definitions/param_image"
        },
        {
          "$ref": "#/definitions/param_int"
        },
        {
          "$ref": "#/definitions/param_list_int"
        },
        {
          "$ref": "#/definitions/param_prev_frame"
        },
        {
          "$ref": "#/definitions/param_source"
        },
        {
          "$ref": "#/definitions/param_text"
        },
        {
          "$ref": "#/definitions/param_time"
        }
      ]
    },
    "param_audiolevel": {
      "additionalProperties": false,
      "description": "Audio-level aware parameter\n\nShader equivalent: `uniform float`",
      "properties": {
        "description": {
          "type": "string"
        },
        "devmode": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "boolean"
        },
        "label": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "string"
        },
        "name": {
          "description": "Name of the field. It *must* be the same as the associated variable in the shader.",
          "type": "string"
        },
        "type": {
          "const": "audiolevel",
          "type": "string"
        }
      },
      "required": [
        "name",
        "type"
      ],
      "type": "object"
    },
    "param_bool": {
      "additionalProperties": false,
      "description": "Boolean parameter\n\nShader equivalent: `uniform bool`",
      "properties": {
        "default": {
          "type": "boolean"
        },
        "description": {
          "type": "string"
        },
        "devmode": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "boolean"
        },
        "label": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "string"
        },
        "name": {
          "description": "Name of the field. It *must* be the same as the associated variable in the shader.",
          "type": "string"
        },
        "type": {
          "const": "bool",
          "type": "string"
        }
      },
      "required": [
        "default",
        "name",
        "type"
      ],
      "type": "object"
    },
    "param_color": {
      "additionalProperties": false,
      "description": "Color parameter\n\nShader equivalent: `uniform float4`",
      "properties": {
        "default": {
          "anyOf": [
            {
              "$ref": "#/definitions/ColorRGB"
            },
            {
              "$ref": "#/definitions/ColorARGB"
            }
          ],
          "description": "Format: #RRGGBB or #AARRGGBB If alpha is not present, full opacity will be used"
        },
        "description": {
          "type": "string"
        },
        "devmode": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "boolean"
        },
        "label": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "string"
        },
        "name": {
          "description": "Name of the field. It *must* be the same as the associated variable in the shader.",
          "type": "string"
        },
        "type": {
          "const": "color",
          "type": "string"
        }
      },
      "required": [
        "default",
        "name",
        "type"
      ],
      "type": "object"
    },
    "param_float": {
      "additionalProperties": false,
      "description": "Float/Double parameter\n\nShader equivalent: `uniform float`",
      "properties": {
        "default": {
          "type": "number"
        },
        "description": {
          "type": "string"
        },
        "devmode": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "boolean"
        },
        "label": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "string"
        },
        "max": {
          "default": 100,
          "description": "Maximum value of the parameter",
          "type": "number"
        },
        "min": {
          "default": 0,
          "description": "Minimum value of the parameter",
          "type": "number"
        },
        "name": {
          "description": "Name of the field. It *must* be the same as the associated variable in the shader.",
          "type": "string"
        },
        "slider": {
          "description": "Show a slider in the UI",
          "type": "boolean"
        },
        "step": {
          "default": 0.01,
          "description": "Smaller step allowed",
          "type": "number"
        },
        "type": {
          "enum": [
            "float",
            "double"
          ],
          "type": "string"
        }
      },
      "required": [
        "default",
        "name",
        "type"
      ],
      "type": "object"
    },
    "param_image": {
      "additionalProperties": false,
      "description": "Image parameter.\n\nShader equivalent: `uniform texture2d`\n\nIt can be either a bundled image in your effect (e.g. a font map to draw text),a file input in the filter properties, or both.",
      "properties": {
        "allow_custom": {
          "default": true,
          "description": "Allow to select an image with a file picker in the effect properties UI.",
          "type": "boolean"
        },
        "default": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "devmode": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "boolean"
        },
        "hidden": {
          "default": false,
          "description": "Hide the UI field",
          "type": "boolean"
        },
        "label": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "string"
        },
        "name": {
          "description": "Name of the field. It *must* be the same as the associated variable in the shader.",
          "type": "string"
        },
        "type": {
          "const": "image",
          "type": "string"
        },
        "values": {
          "default": null,
          "description": "Optional list of pre-defined images.\n\nThese files must be in the same folder of you effect, or in the same packaged .shadertastic file to be accepted\n\nIf `allowed_custom` is true, another pick \"Use custom file\" will also be available in the UI.",
          "items": {
            "additionalProperties": false,
            "properties": {
              "label": {
                "type": "string"
              },
              "value": {
                "type": "string"
              }
            },
            "required": [
              "label",
              "value"
            ],
            "type": "object"
          },
          "type": "array"
        }
      },
      "required": [
        "default",
        "name",
        "type"
      ],
      "type": "object"
    },
    "param_int": {
      "additionalProperties": false,
      "description": "Integer parameter\n\nShader equivalent: `uniform int`",
      "properties": {
        "default": {
          "type": "number"
        },
        "description": {
          "type": "string"
        },
        "devmode": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "boolean"
        },
        "label": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "string"
        },
        "max": {
          "description": "Maximum value of the parameter. If not set, 100 will be used",
          "type": "number"
        },
        "min": {
          "description": "Minimum value of the parameter. If not set, 0.0 will be used",
          "type": "number"
        },
        "name": {
          "description": "Name of the field. It *must* be the same as the associated variable in the shader.",
          "type": "string"
        },
        "slider": {
          "description": "Show a slider in the UI",
          "type": "boolean"
        },
        "step": {
          "description": "Smaller step allowed. If not set, 1 will be used",
          "type": "number"
        },
        "type": {
          "const": "int",
          "type": "string"
        }
      },
      "required": [
        "default",
        "name",
        "type"
      ],
      "type": "object"
    },
    "param_list_int": {
      "additionalProperties": false,
      "description": "List of Integers parameter\n\nShader equivalent: `uniform int`",
      "properties": {
        "default": {
          "type": "number"
        },
        "description": {
          "type": "string"
        },
        "devmode": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "boolean"
        },
        "label": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "string"
        },
        "name": {
          "description": "Name of the field. It *must* be the same as the associated variable in the shader.",
          "type": "string"
        },
        "type": {
          "const": "list_int",
          "type": "string"
        },
        "values": {
          "description": "List of values available",
          "items": {
            "additionalProperties": false,
            "properties": {
              "label": {
                "type": "string"
              },
              "value": {
                "type": "number"
              }
            },
            "required": [
              "label",
              "value"
            ],
            "type": "object"
          },
          "type": "array"
        }
      },
      "required": [
        "default",
        "name",
        "type",
        "values"
      ],
      "type": "object"
    },
    "param_prev_frame": {
      "additionalProperties": false,
      "description": "Save the previous frame of a specific step as a parameter\n\nShader equivalent: `uniform texture2d`",
      "properties": {
        "description": {
          "type": "string"
        },
        "devmode": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "boolean"
        },
        "label": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "string"
        },
        "name": {
          "description": "Name of the field. It *must* be the same as the associated variable in the shader.",
          "type": "string"
        },
        "step": {
          "description": "The step to keep as a previous frame. It must be less or equal to the number of steps defined in the effect root metadata.",
          "type": "number"
        },
        "type": {
          "const": "prev_frame",
          "type": "string"
        }
      },
      "required": [
        "name",
        "step",
        "type"
      ],
      "type": "object"
    },
    "param_source": {
      "additionalProperties": false,
      "description": "Video Source parameter\n\nShader equivalent: `uniform texture2d`",
      "properties": {
        "description": {
          "type": "string"
        },
        "devmode": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "boolean"
        },
        "label": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "string"
        },
        "name": {
          "description": "Name of the field. It *must* be the same as the associated variable in the shader.",
          "type": "string"
        },
        "type": {
          "const": "source",
          "type": "string"
        }
      },
      "required": [
        "name",
        "type"
      ],
      "type": "object"
    },
    "param_text": {
      "additionalProperties": false,
      "description": "Show some text in the properties UI\n\nShader equivalent: none",
      "properties": {
        "description": {
          "type": "string"
        },
        "devmode": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "boolean"
        },
        "label": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "string"
        },
        "name": {
          "description": "Name of the field. It *must* be the same as the associated variable in the shader.",
          "type": "string"
        },
        "type": {
          "const": "text",
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "type",
        "value"
      ],
      "type": "object"
    },
    "param_time": {
      "additionalProperties": false,
      "description": "Execution time of the effect, in seconds. An optional speed input is provided to accelerate the effect. Also, the time can be reset to zero when the filter is toggled as visible\n\nShader equivalent: `uniform float`",
      "properties": {
        "description": {
          "type": "string"
        },
        "devmode": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "boolean"
        },
        "label": {
          "description": "If set to true, this field will only be available in the property UI if the developer mode is active.",
          "type": "string"
        },
        "name": {
          "description": "Name of the field. It *must* be the same as the associated variable in the shader.",
          "type": "string"
        },
        "reset_on_show": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "const": "prompt",
              "type": "string"
            }
          ],
          "default": false,
          "description": "If true, the time will be reset to zero when the filter is set visible. If \"prompt\", let the user decide by showing an input in the property UI."
        },
        "speed": {
          "additionalProperties": false,
          "description": "Speed options",
          "properties": {
            "default": {
              "default": ": 1.0",
              "type": "number"
            },
            "label": {
              "default": ": \"Speed\"",
              "description": "If show, name of the input in the properties UI",
              "type": "string"
            },
            "max": {
              "default": ": 1.0",
              "description": "Maximum allowed speed",
              "type": "number"
            },
            "min": {
              "default": ": 0.0",
              "description": "Minimum allowed speed",
              "type": "number"
            },
            "show_ui": {
              "default": ": true",
              "description": "If true, the time will be reset to zero when the filter is set visible. If \"prompt\", let the user decide by showing an input in the property UI.",
              "type": "boolean"
            }
          },
          "required": [
            "show_ui",
            "min",
            "max",
            "default"
          ],
          "type": "object"
        },
        "type": {
          "const": "time",
          "type": "string"
        }
      },
      "required": [
        "name",
        "type"
      ],
      "type": "object"
    }
  }
}

=== NaGeLBailey/shadertastic/data/effects/transitions/pixelate/meta.json
{
  "about": {
    "author_name": "xurei",
    "author_url": "http://about.xurei.io",
    "description": "Pixelate scene and unpixelate to the other"
  },
  "metafileVersion": 1,
  "label": "Pixelate",
  "parameters": [
    {
      "name": "break_point",
      "label": "Breaking point",
      "type": "float",
      "slider": true,
      "min": 0.0,
      "max": 1.0,
      "step": 0.01,
      "default": 0.5
    },
    {
      "name": "max_pixelation_level",
      "label": "Max Pixelation level",
      "type": "float",
      "slider": true,
      "min": 0.1,
      "max": 10,
      "default": 5
    }
  ]
}

=== NaGeLBailey/shadertastic/data/effects/filters/face_detection_zoom/meta.json
{
  "about": {
    "author_name": "xurei",
    "author_url": "http://about.xurei.io"
  },
  "label": "[Face Detection] Zoom to face",
  "steps": 1,
  "input_time": false,
  "input_facedetection": true,
  "parameters": [
    {
      "name": "zoom_level",
      "label": "Zoom level",
      "description": "prout",
      "type": "double",
      "slider": true,
      "min": 0,
      "max": 3.0,
      "default": 0.9,
      "step": 0.001
    },
    {
      "name": "show_ref_points",
      "label": "Show ref. points (devmode)",
      "type": "bool",
      "devmode": true,
      "default": false
    },
    {
      "name": "preserve_aspect_ratio",
      "label": "Preserve aspect ratio",
      "type": "bool",
      "default": true
    }
  ]
}

=== NaGeLBailey/shadertastic/data/effects/filters/gaussianblur/meta.json
{
  "about": {
    "author_name": "xurei",
    "author_url": "http://about.xurei.io"
  },
  "label": "Gaussian Blur",
  "steps": 2,
  "parameters": [
    {
      "name": "blur_level_x",
      "label": "Blur level (X)",
      "type": "int",
      "slider": true,
      "min": 0,
      "max": 100,
      "default": 10
    },
    {
      "name": "blur_level_y",
      "label": "Blur level (Y)",
      "type": "int",
      "slider": true,
      "min": 0,
      "max": 100,
      "default": 10
    }
  ]
}

=== NaGeLBailey/shadertastic/data/effects/transitions/burn/meta.json
{
  "about": {
    "author_name": "xurei",
    "author_url": "http://about.xurei.io"
  },
  "metafileVersion": 1,
  "label": "Burn",
  "revision": 2,
  "steps": 1,
  "parameters": [
    {
      "name": "transition_point",
      "label": "Transition point",
      "type": "float",
      "slider": true,
      "min": 0.0,
      "max": 1.0,
      "step": 0.01,
      "default": 0.5
    },
    {
      "name": "random_noise",
      "label": "Random Noise",
      "type": "float",
      "slider": true,
      "min": 0.0,
      "max": 1.0,
      "step": 0.01,
      "default": 0.1
    }
  ]
}

=== NaGeLBailey/shadertastic/data/effects/filters/displacement_map_source/meta.json
{
  "about": {
    "author_name": "xurei",
    "author_url": "http://about.xurei.io"
  },
  "label": "Displacement Map (Source)",
  "steps": 1,
  "parameters": [
    {
      "name": "displace_mode",
      "label": "Displace mode",
      "type": "list_int",
      "values": [
        {"label": "Single (default)", "value": 0},
        {"label": "Displace + Overlay", "value": 1}
      ],
      "default": 0
    },
    {
      "name": "displace_mode_text",
      "label": "",
      "type": "text",
      "value": "In 'Single' mode, the whole source is used as a displacement map.\nIn 'Displace + Overlay' mode, the left half of the source is used as a displacement map and the right half is used as an overlay."
    },
    {
      "name": "color_space",
      "label": "Color Space",
      "type": "list_int",
      "values": [
        {"label": "RGB", "value": 0},
        {"label": "YUV", "value": 1}
      ],
      "default": 1
    },
    {
      "name": "color_space_text",
      "label": "",
      "type": "text",
      "value": "In RGB color space, #808080 is the zero (i.e. no displacement) value. The R and G component define the amount of displacement of a pixel in X and Y, respectively.\nIn YUV color space, any grey color is a zero displacement color. The U and V components define the amount of displacement of a pixel in X and Y, respectively."
    },
    {
      "name": "sampler_mode",
      "label": "Border method",
      "type": "list_int",
      "values": [
        {"label": "Clamp", "value": 0},
        {"label": "Mirror", "value": 1},
        {"label": "Repeat", "value": 2}
      ],
      "default": 0
    },
    {
      "name": "displacement_strength_x",
      "label": "Strength X",
      "type": "float",
      "slider": true,
      "min": 0,
      "max": 2.0,
      "default": 0.35,
      "step": 0.005
    },
    {
      "name": "displacement_strength_y",
      "label": "Strength Y",
      "type": "float",
      "slider": true,
      "min": 0,
      "max": 2.0,
      "default": 0.35,
      "step": 0.005
    },
    {
      "name": "displacement_map",
      "label": "Displacement Map",
      "type": "source"
    }
  ]
}
